
services:
  nexus-os:
    container_name: nexus-os
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Database connection string (using the service name 'db' as hostname)
      - DATABASE_URL=postgresql://nexus:securepassword@db:5432/nexus_os?schema=public
      # Next Auth Secret (Generate a new one for production!)
      - AUTH_SECRET=change_me_in_production_to_a_long_random_string
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://167.126.15.187:3000
    depends_on:
      - db
    networks:
      - nexus-network

  db:
    container_name: nexus-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=nexus
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=nexus_os
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexus-network



networks:
  nexus-network:
    driver: bridge

volumes:
  postgres_data:
